services:
  app:
    build: .
    restart: "no"
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: "mongodb://mongo:27017/realworld"
    env_file:
      - .env
    depends_on:
      - mongo
    volumes:
      - ./app:/app/app
      - ./pyproject.toml:/app/pyproject.toml
      - ./poetry.lock:/app/poetry.lock
      - poetry-cache:/app/.venv

  mongo:
    image: mongo:6.0
    restart: "no"
    command: --quiet --logpath /dev/null
    ports:
      - "27017:27017"
    env_file:
      - .env
    volumes:
      - ./mongo-data:/data/db

volumes:
  poetry-cache:
